use new users-api endpoint for fetching occupations, flat list
Virtual-Finland-Development/external-service-demo pull request #21
Opened 2022-12-21 13:27 UTC by LauriGofore

https://virtualfindev.atlassian.net/browse/VFD-163

2022-12-21 16:33 UTC, lsipii requested changes
Tälle repolle voisi ajaa mukavuus-syistä komennon: `npm audit fix`, ainakin critical issuet.

2022-12-21 17:20 UTC, lsipii commented
Sain tsekattua lokaalissa että asia pelitteleepi: piti tehdä testbed-api:hin [muutos](https://github.com/Virtual-Finland-Development/testbed-api/commit/e3a036f5ae9b19fbbe7f62c56c7ebdd131cfc2ad) että kun ajelee lokaalissa esim. docker composella niin voi käyttää lokaalin users-api:n endpointteja, ja sit ajaessa testiä yliajaa env-valuen: `REACT_APP_TESTBED_API_BASE_URL=http://localhost:3003 npm run start`

👍

2022-12-22 06:28 UTC, LauriGofore commented
> Tälle repolle voisi ajaa mukavuus-syistä komennon: `npm audit fix`, ainakin critical issuet.

Tämä nyt ajettu, critical issuet fiksattu. Kun lähti tuolle "use the force" -polulle, niin siitä alkoi sellainen loputon luuppi mitä ei saanut selvitetyksi.

2022-12-22 07:09 UTC, lsipii approved these changes

2022-12-22 07:50 UTC, merged